---
title: "NOAA National Climatic Data Center"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


```{r dataset, message=FALSE}
data(instcart)

aislenumber = instacart %>% 
  count(aisle, name = "count") %>% 
  arrange(desc(count)) %>% 
  filter(count > 10000) %>% 
  mutate(
    rank = c(1:length(aisle)),
    aisle = fct_reorder(aisle , rank)
        )

```


Column {data-width=650}
-----------------------------------------------------------------------

### Aisle Count

```{r}
aislenumber %>%
  mutate(text_label = str_c("count: ", count, "\nrank: ", rank)) %>% plot_ly(
    x = ~aisle, y = ~count, type = "bar", mode = "markers",
    color = ~aisle, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Order Hour of the Day among Top Aisles

```{r}
common_aisle =
  instacart %>% 
  count(aisle, sort = TRUE,name = "count") %>% 
  top_n(8) %>% 
  select(aisle)

inner_join(instacart, common_aisle, by = "aisle") %>% 
  select(order_hour_of_day, aisle) %>% 
  mutate(aisle = fct_reorder(aisle,order_hour_of_day)) %>% 
  plot_ly(
    y = ~order_hour_of_day, color = ~aisle, type = "box",
    colors = "Set2") 
  
 
```

### Count of Locations where Difference between Tmax and Tmin larger than 10 centigrade

```{r}
common = inner_join(instacart, common_aisle, by = "aisle") %>% 
  filter(aisle == "milk"| aisle == "fresh vegetables"| aisle == "fresh fruits"| aisle == "packaged vegetables fruits"| aisle == "yogurt"| aisle == "packaged cheese"| aisle == "water seltzer sparkling water"| aisle == "chips pretzels") %>% 
  group_by(order_hour_of_day,aisle) %>% 
  summarise(
    count = n()
  )
common %>% 
  mutate(text_label = str_c("hour: ", order_hour_of_day, '\ncount: ', count)) %>% 
  plot_ly(
    x = ~order_hour_of_day, y = ~count, color = ~aisle, type = "scatter", text = ~text_label, alpha = 0.8) %>%  
add_lines(linetype = ~aisle)
```

